/* notes.js — Comprehensive UPSC ISS Revision Notes */
const REVISION_NOTES = {
    "paper1": {
        "prob": {
            "title": "Probability & Statistical Methods",
            "sections": [
                {
                    "id": "foundations",
                    "label": "Probability Foundations",
                    "content": "### Axiomatic & Classical Definitions\n- **Axioms:** \\( P(A) \\ge 0 \\), \\( P(S) = 1 \\), and for disjoint \\( A_i \\), \\( P(\\cup A_i) = \\sum P(A_i) \\).\n- **Bayes' Theorem:** Posterior calculation \\( P(B_k|A) = \\frac{P(A|B_k)P(B_k)}{\\sum P(A|B_i)P(B_i)} \\).\n\n### Random Variables & Moments\n- **Moments:** \n  - Raw: \\( \\mu'_r = E(X^r) \\). Central: \\( \\mu_r = E(X-\\mu)^r \\).\n  - Relation: \\( \\mu_2 = \\mu'_2 - (\\mu'_1)^2 \\), \\( \\mu_3 = \\mu'_3 - 3\\mu'_2\\mu'_1 + 2(\\mu'_1)^3 \\).\n- **Expectation:** \\( E(X) = E[E(X|Y)] \\). \\( Var(X) = E[Var(X|Y)] + Var[E(X|Y)] \\).\n\n`ISS Trick:` If \\( X, Y \\) are i.i.d. \\( N(0, 1) \\), then \\( X+Y \\) and \\( X-Y \\) are independent (Basu's Theorem context)."
                },
                {
                    "id": "discrete-dist",
                    "label": "Standard Discrete Distributions",
                    "content": "### Key Discrete Models\n- **Bernoulli(p)**: \\( P(X=x)=p^x q^{1-x} \\)\n  - **Gen. Functions**: PGF: \\( q+ps \\), MGF: \\( q+pe^t \\), CF: \\( q+pe^{it} \\)\n  - **Shape/Median**: \\( \\gamma_1 = \\frac{1-2p}{\\sqrt{pq}} \\), \\( \\beta_2 = \\frac{1-6pq}{pq} \\), Median: 0 (if \\( p<0.5 \\)) or 1 (if \\( p>0.5 \\)).\n- **Binomial(n,p)**: \\( \\binom{n}{x}p^x q^{n-x} \\)\n  - **Gen. Functions**: PGF: \\( (q+ps)^n \\), MGF: \\( (q+pe^t)^n \\), Cumulants: \\( \\kappa_r = n \\kappa_{r,Bern} \\).\n  - **Shape/Median**: \\( \\gamma_1 = \\frac{q-p}{\\sqrt{npq}} \\), \\( \\beta_2 = 3 + \\frac{1-6pq}{npq} \\), Median: \\( \\approx np \\).\n- **Poisson(\\(\\lambda\\))**: \\( \\frac{e^{-\\lambda}\\lambda^x}{x!} \\)\n  - **Gen. Functions**: PGF: \\( e^{\\lambda(s-1)} \\), MGF: \\( e^{\\lambda(e^t-1)} \\), Cumulants: \\( \\kappa_r = \\lambda \\) for all \\( r \\).\n  - **Shape/Median**: \\( \\gamma_1 = 1/\\sqrt{\\lambda} \\), \\( \\beta_2 = 3 + 1/\\lambda \\), Median: \\( \\lfloor \\lambda + \\lambda/3 - 0.02 \\rfloor \\).\n- **Geometric(p)**: \\( q^x p \\) (for \\( x \\ge 0 \\))\n  - **Gen. Functions**: PGF: \\( p(1-qs)^{-1} \\), MGF: \\( p(1-qe^t)^{-1} \\).\n  - **Shape/Median**: \\( \\gamma_1 = \\frac{1+q}{\\sqrt{q}} \\), \\( \\beta_2 = 3 + \\frac{p^2+6q}{q} \\), Median: \\( \\lceil -\\frac{\\log 2}{\\log q} \\rceil \\).\n- **Negative Binomial(r,p)**: \\( \\binom{x+r-1}{x}p^r q^x \\)\n  - **Gen. Functions**: PGF: \\( (p/(1-qs))^r \\), MGF: \\( (p/(1-qe^t))^r \\), Cumulants: \\( \\kappa_r = r \\kappa_{r,Geo} \\).\n  - **Shape/Median**: \\( \\gamma_1 = \\frac{1+q}{\\sqrt{rq}} \\), \\( \\beta_2 = 3 + \\frac{p^2+6q}{rq} \\).\n- **Hypergeometric(N,M,n)**: \\( E(X)=nM/N \\), \\( Var(X)=n\\frac{M}{N}\\frac{N-M}{N}\\frac{N-n}{N-1} \\).\n- **Multinomial**: MGF: \\( (p_1 e^{t_1} + ... + p_k e^{t_k})^n \\)."
                },
                {
                    "id": "continuous-dist",
                    "label": "Standard Continuous Distributions",
                    "content": "### Key Continuous Models\n- **Uniform/Rectangular(a,b)**: \\( f(x) = 1/(b-a) \\)\n  - **Gen. Functions**: MGF: \\( \\frac{e^{tb}-e^{ta}}{t(b-a)} \\).\n  - **Properties**: Median: \\( (a+b)/2 \\), \\( \\gamma_1 = 0 \\), \\( \\beta_2 = 1.8 \\).\n- **Exponential(\\(\\theta\\))**: \\( \\theta e^{-\\theta x} \\)\n  - **Gen. Functions**: MGF: \\( (1-t/\\theta)^{-1} \\).\n  - **Properties**: Median: \\( \\frac{\\ln 2}{\\theta} \\), \\( \\gamma_1 = 2 \\), \\( \\beta_2 = 9 \\).\n- **Normal(\\(\\mu, \\sigma^2\\))**:\n  - **Gen. Functions**: MGF: \\( e^{\\mu t + \\frac{1}{2}\\sigma^2 t^2} \\), CF: \\( e^{i\\mu t - \\frac{1}{2}\\sigma^2 t^2} \\).\n  - **Cumulants**: \\( \\kappa_1 = \\mu, \\kappa_2 = \\sigma^2, \\kappa_{r>2} = 0 \\).\n  - **Properties**: Median: \\( \\mu \\), \\( \\gamma_1 = 0 \\), \\( \\beta_2 = 3 \\).\n- **Cauchy**: \\( \\frac{1}{\\pi[1+(x-\\mu)^2]} \\)\n  - **Gen. Functions**: CF: \\( e^{i\\mu t - |t|} \\), MGF does not exist.\n  - **Properties**: Median: \\( \\mu \\), Moments do not exist.\n- **Laplace(\\(\\mu, b\\))**: \\( \\frac{1}{2b} e^{-|x-\\mu|/b} \\)\n  - **Gen. Functions**: MGF: \\( \\frac{e^{\\mu t}}{1-b^2 t^2} \\).\n  - **Properties**: Median: \\( \\mu \\), \\( \\gamma_1 = 0 \\), \\( \\beta_2 = 6 \\).\n- **Gamma(\\(\\alpha, \\lambda\\))**: \\( \\frac{\\lambda^\\alpha}{\\Gamma(\\alpha)} x^{\\alpha-1} e^{-\\lambda x} \\)\n  - **Gen. Functions**: MGF: \\( (1-t/\\lambda)^{-\\alpha} \\).\n  - **Properties**: \\( \\gamma_1 = 2/\\sqrt{\\alpha} \\), \\( \\beta_2 = 3 + 6/\\alpha \\).\n- **Beta Type I**: \\( \\frac{x^{m-1}(1-x)^{n-1}}{B(m,n)} \\) on \\( [0, 1] \\)\n  - **Properties**: \\( E(X) = \\frac{m}{m+n} \\), \\( Var(X) = \\frac{mn}{(m+n)^2(m+n+1)} \\).\n- **Beta Type II**: \\( \\frac{x^{m-1}}{B(m,n)(1+x)^{m+n}} \\) on \\( [0, \\infty) \\)\n  - **Properties**: \\( E(X) = \\frac{m}{n-1} \\) (for \\( n>1 \\)).\n- **Lognormal**: \\( \\ln X \\sim N(\\mu, \\sigma^2) \\)\n  - **Properties**: \\( E(X) = e^{\\mu + \\sigma^2/2} \\), Median: \\( e^\\mu \\), Mode: \\( e^{\\mu - \\sigma^2} \\)."
                },
                {
                    "id": "generating-functions",
                    "label": "General Generating Functions",
                    "content": "### General Formulas\n- **MGF:** \\( M_X(t) = \\sum \\frac{\\mu'_r t^r}{r!} \\). \\( \\mu'_r = [\\frac{d^r}{dt^r} M_X(t)]_{t=0} \\).\n- **Cumulant GF:** \\( K_X(t) = \\ln M_X(t) = \\sum \\frac{\\kappa_r t^r}{r!} \\).\n  - \\( \\kappa_1 = \\mu'_1 \\), \\( \\kappa_2 = \\mu_2 \\), \\( \\kappa_3 = \\mu_3 \\), \\( \\kappa_4 = \\mu_4 - 3\\mu_2^2 \\).\n- **PGF:** \\( G_X(s) = E(s^X) \\). \\( P(X=k) = \\frac{1}{k!} G^{(k)}(0) \\).\n- **Characteristic Function (CF):** \\( \\phi_X(t) = E(e^{itX}) \\). CF of sum = Product of CFs."
                },
                {
                    "id": "descriptive-stats",
                    "label": "Statistical Methods: Descriptive",
                    "content": "### Summary Measures\n- **Location:** Mean, Median, Mode. Empirical: \\( \\text{Mode} \\approx 3\\text{Median} - 2\\text{Mean} \\).\n- **Dispersion:** SD, Variance, CV (\\( \\sigma/\\bar{x} \\times 100 \\)).\n- **Skewness:** \\( \\gamma_1 = \\mu_3 / \\sigma^3 \\). Positive if tail is to the right.\n- **Kurtosis:** \\( \\beta_2 = \\mu_4 / \\sigma^4 \\). Mesokurtic (\\( \\beta_2=3 \\)), Leptokurtic (\\( >3 \\)), Platykurtic (\\( <3 \\)).\n\n### Frequency Data\n- **Association:** Chi-square test for contingency tables. Yule's coefficient \\( Q = \\frac{ad-bc}{ad+bc} \\).\n- **Curve Fitting:** Method of Least Squares. Orthogonal polynomials used for polynomial regression."
                },
                {
                    "id": "correlation-regression",
                    "label": "Correlation & Regression",
                    "content": "### Bivariate Analysis\n- **Correlation (r):** \\( r = \\frac{Cov(X,Y)}{\\sigma_x \\sigma_y} \\). Invariant to change of scale/origin (except sign).\n- **Regression Lines:** Intersect at \\( (\\bar{x}, \\bar{y}) \\). Slope \\( b_{yx} = r \\frac{\\sigma_y}{\\sigma_x} \\).\n- **Multiple Correlation (R):** Measures linear relationship between one variable and a set of others. \\( 0 \\le R \\le 1 \\).\n- **Partial Correlation (r12.3):** Correlation between 1 and 2 after removing linear effect of 3.\n- **Intraclass Correlation:** Correlation between members of a cluster. Bounds: \\( -1/(k-1) \\le \\rho \\le 1 \\).\n- **Correlation Ratio (\\( \\eta \\)):** Measures general (non-linear) relationship. \\( \\eta^2 \\ge r^2 \\)."
                },
                {
                    "id": "sampling-dist",
                    "label": "Sampling Distributions & Tests",
                    "content": "### Sampling Distributions\n- **Chi-square (\\(\\chi^2\\)):** Sum of squares of \\( n \\) i.i.d. \\( N(0,1) \\). Mean \\( n \\), Var \\( 2n \\).\n- **t-distribution:** \\( t = Z / \\sqrt{\\chi^2/n} \\). Symmetric, heavier tails than Normal.\n- **F-distribution:** Ratio of two independent \\( \\chi^2/df \\). \\( F_{n,m} = 1/F_{m,n} \\).\n\n### Tests of Significance\n- **Large Sample:** Z-tests for means and proportions. Standard Error (SE) is critical.\n- **Small Sample:** t-tests for mean/difference, paired t-test. F-test for equality of variances.\n- **Sampling distribution of r:** \\( t = \\frac{r\\sqrt{n-2}}{\\sqrt{1-r^2}} \\sim t_{n-2} \\)."
                },
                {
                    "id": "non-parametric",
                    "label": "Non-parametric & Order Stats",
                    "content": "### Detailed Non-parametric Formulas\n- **Sign Test**: Under \\( H_0, S \\sim B(n, 0.5) \\).\n- **Median Test**: 2x2 contingency table using Chi-square/Fisher's exact.\n- **Run Test**: Total runs \\( R \\). Under \\( H_0 \\):\n  - \\( E(R) = \\frac{2n_1 n_2}{n_1+n_2} + 1 \\)\n  - \\( Var(R) = \\frac{2n_1 n_2(2n_1 n_2 - n_1 - n_2)}{(n_1+n_2)^2(n_1+n_2-1)} \\)\n- **Wilcoxon Signed Rank**: Sum of ranks \\( W \\).\n  - \\( E(W) = \\frac{n(n+1)}{4} \\)\n  - \\( Var(W) = \\frac{n(n+1)(2n+1)}{24} \\)\n- **Mann-Whitney U**: Sum of ranks \\( U \\).\n  - \\( E(U) = \\frac{n_1 n_2}{2} \\)\n  - \\( Var(U) = \\frac{n_1 n_2(n_1+n_2+1)}{12} \\)\n- **Wald-Wolfowitz**: Runs on ordered combined samples.\n- **Kolmogorov-Smirnov (K-S)**:\n  - **One-Sample**: \\( D_n = \\sup_x |F_n(x) - F_0(x)| \\).\n  - **Two-Sample**: \\( D_{m,n} = \\sup_x |F_m(x) - G_n(x)| \\)."
                }
            ],
            "tips": "ISS Paper I Focus: \n1. Memorize standard error (SE) formulas for all large sample tests. \n2. Relationships between \\( \\chi^2, t, \\) and \\( F \\) are high-yield. \n3. In non-parametric tests, know the 'Null Hypothesis' for each (e.g., Run test is for randomness). \n4. Remember: Partial correlation is ALWAYS between -1 and 1, but Multiple correlation is ALWAYS between 0 and 1. \n5. Jacobian is a must for transformation problems!"
        },
"num": {
    "title": "Numerical Analysis",
    "sections": [
        {
            "id": "num-finite-diff",
            "label": "Finite Differences & Operators",
            "content": "## Finite Differences & Operators\n\n### The Three Core Operators\n\n| Operator | Symbol | Definition |\n|---|---|---|\n| Forward Difference | \\(\\Delta\\) | \\(\\Delta f(x) = f(x+h) - f(x)\\) |\n| Backward Difference | \\(\\nabla\\) | \\(\\nabla f(x) = f(x) - f(x-h)\\) |\n| Shift | \\(E\\) | \\(E\\,f(x) = f(x+h)\\) |\n| Central Difference | \\(\\delta\\) | \\(\\delta f(x) = f(x+h/2) - f(x-h/2)\\) |\n\n### Key Operator Relations\n\n\\[\n\\Delta = E - 1 \\quad\\Rightarrow\\quad E = 1 + \\Delta\n\\]\n\\[\n\\nabla = 1 - E^{-1} \\quad\\Rightarrow\\quad E^{-1} = 1 - \\nabla\n\\]\n\\[\n\\Delta \\equiv E - 1, \\quad \\nabla \\equiv 1 - E^{-1}, \\quad \\delta \\equiv E^{1/2} - E^{-1/2}\n\\]\n\n**Averaging operator** \\(\\mu\\):\n\\[\n\\mu\\,f(x) = \\tfrac{1}{2}\\bigl[f(x+h/2) + f(x-h/2)\\bigr]\n\\]\n\n### Higher-Order Forward Differences\n\n\\[\n\\Delta^n f(x) = \\sum_{r=0}^{n} (-1)^{n-r}\\binom{n}{r} f(x+rh)\n\\]\n\n**Differences of zero** (useful for polynomial recognition):\n\\[\n\\Delta^n(0) = \\sum_{r=0}^{n}(-1)^{n-r}\\binom{n}{r}r^n = n!\n\\]\nFor a polynomial of degree \\(n\\): \\(\\Delta^n f\\) = constant, \\(\\Delta^{n+1} f = 0\\).\n\n### Factorial Notation\n\n\\[\nx^{(n)} = x(x-1)(x-2)\\cdots(x-n+1) \\quad \\text{(falling factorial)}\n\\]\n\\[\n\\Delta\\, x^{(n)} = n\\, x^{(n-1)}\n\\]\nAny polynomial can be written in factorial form — this simplifies differencing enormously.\n\n### Separation of Symbols\n\nSince \\(E = e^{hD}\\) (where \\(D = d/dx\\)):\n\\[\n\\Delta = e^{hD} - 1, \\qquad hD = \\ln(1+\\Delta)\n\\]\nUseful for converting between difference and differential operators.\n\n### Sub-division of Intervals\n\nIf the interval is subdivided from \\(h\\) to \\(h/m\\), use \\(E^{1/m}\\) and the relation:\n\\[\n\\Delta_h = \\Delta_{h/m}^m\n\\]\n\n> **ISS tip:** Questions frequently test: identifying the degree of a polynomial from its difference table, operator algebra (simplify \\(\\Delta^2 E\\), etc.), and differences of zero."
        },
        {
            "id": "num-interpolation-equal",
            "label": "Interpolation — Equal Intervals",
            "content": "## Interpolation for Equal Intervals\n\nAll formulae below use \\( p = (x - x_0)/h \\) as the substitution variable.\n\n---\n\n### Newton–Gregory Forward Interpolation\n\n**Use:** \\(x\\) near the **beginning** of the table.\n\n\\[\nf(x) = f_0 + p\\,\\Delta f_0 + \\frac{p(p-1)}{2!}\\Delta^2 f_0 + \\frac{p(p-1)(p-2)}{3!}\\Delta^3 f_0 + \\cdots\n\\]\n\nwhere \\(p = \\dfrac{x - x_0}{h}\\), \\(\\;0 < p < 1\\) for interpolation.\n\n**Error term:**\n\\[\nR_n = \\frac{p(p-1)\\cdots(p-n)}{(n+1)!}\\,h^{n+1}\\,f^{(n+1)}(\\xi)\n\\]\n\n---\n\n### Newton–Gregory Backward Interpolation\n\n**Use:** \\(x\\) near the **end** of the table.\n\nLet \\( p = (x - x_n)/h \\) (here \\(p\\) is negative for backward interpolation from the last entry).\n\n\\[\nf(x) = f_n + p\\,\\nabla f_n + \\frac{p(p+1)}{2!}\\nabla^2 f_n + \\frac{p(p+1)(p+2)}{3!}\\nabla^3 f_n + \\cdots\n\\]\n\n---\n\n### Central Difference Formulae (middle of table)\n\n**Gauss Forward Formula** (\\(0 < p < 1\\)):\n\\[\nf(x) = f_0 + p\\,\\delta f_{1/2} + \\frac{p(p-1)}{2!}\\delta^2 f_0 + \\frac{(p+1)p(p-1)}{3!}\\delta^3 f_{1/2} + \\cdots\n\\]\n\n**Gauss Backward Formula** (\\(-1 < p < 0\\)):\n\\[\nf(x) = f_0 + p\\,\\delta f_{-1/2} + \\frac{p(p+1)}{2!}\\delta^2 f_0 + \\frac{(p+1)p(p-1)}{3!}\\delta^3 f_{-1/2} + \\cdots\n\\]\n\n**Stirling's Formula** (average of Gauss forward & backward, best near centre):\n\\[\nf(x) = f_0 + p\\,\\mu\\delta f_0 + \\frac{p^2}{2!}\\delta^2 f_0 + \\frac{p(p^2-1)}{3!}\\mu\\delta^3 f_0 + \\frac{p^2(p^2-1)}{4!}\\delta^4 f_0 + \\cdots\n\\]\n\n**Bessel's Formula** (best when \\(p \\approx 1/2\\)):\n\\[\nf(x) = \\tfrac{1}{2}(f_0+f_1) + \\bigl(p-\\tfrac{1}{2}\\bigr)\\delta f_{1/2} + \\frac{p(p-1)}{2!}\\cdot\\tfrac{1}{2}(\\delta^2 f_0+\\delta^2 f_1) + \\cdots\n\\]\n\n---\n\n### Quick Selection Guide\n\n| \\(p\\) range | Best formula |\n|---|---|\n| Near 0 (start) | Newton–Gregory Forward |\n| Near \\(n\\) (end) | Newton–Gregory Backward |\n| Near 0, going forward | Gauss Forward |\n| Near 0, going backward | Gauss Backward |\n| \\(p \\approx 0\\), symmetric | Stirling |\n| \\(p \\approx 0.5\\) | Bessel |\n\n> **ISS tip:** Know how to compute \\(p\\), build the difference table, and substitute. The error term formula is also frequently tested."
        },
        {
            "id": "num-divided-diff",
            "label": "Divided Differences & Unequal Intervals",
            "content": "## Divided Differences & Lagrange Interpolation\n\n### Divided Differences — Definition\n\n**First order:**\n\\[\nf[x_0, x_1] = \\frac{f(x_1) - f(x_0)}{x_1 - x_0}\n\\]\n\n**Second order:**\n\\[\nf[x_0, x_1, x_2] = \\frac{f[x_1,x_2] - f[x_0,x_1]}{x_2 - x_0}\n\\]\n\n**General \\(n\\)-th order:**\n\\[\nf[x_0,x_1,\\ldots,x_n] = \\frac{f[x_1,\\ldots,x_n] - f[x_0,\\ldots,x_{n-1}]}{x_n - x_0}\n\\]\n\n### Properties of Divided Differences\n\n- **Symmetric** in its arguments: \\(f[x_0,x_1] = f[x_1,x_0]\\)\n- If \\(f(x)\\) is a polynomial of degree \\(n\\), then \\(f[x_0,\\ldots,x_n]\\) = leading coefficient, and \\(f[x_0,\\ldots,x_{n+1}] = 0\\)\n- **Leibniz rule:** \\(\\Delta^n[u\\cdot v]\\) can be expanded similarly to binomial\n- Relation to forward differences (equal spacing): \\(f[x_0,x_1,\\ldots,x_n] = \\dfrac{\\Delta^n f_0}{n!\\,h^n}\\)\n\n### Newton's Divided Difference Interpolation\n\n**Use: unequal intervals** (or any spacing).\n\n\\[\nf(x) = f[x_0] + (x-x_0)f[x_0,x_1] + (x-x_0)(x-x_1)f[x_0,x_1,x_2] + \\cdots\n\\]\n\n\\[\n= \\sum_{k=0}^{n} \\Bigl[\\prod_{j=0}^{k-1}(x-x_j)\\Bigr]\\, f[x_0,\\ldots,x_k]\n\\]\n\n### Lagrange's Interpolation Formula\n\n**Use: unequal intervals; compact form.**\n\n\\[\nf(x) = \\sum_{i=0}^{n} L_i(x)\\, f(x_i)\n\\]\n\nwhere the **Lagrange basis polynomial** is:\n\\[\nL_i(x) = \\prod_{\\substack{j=0 \\\\ j\\neq i}}^{n} \\frac{x - x_j}{x_i - x_j}\n\\]\n\n**Error:**\n\\[\nR_n(x) = \\frac{f^{(n+1)}(\\xi)}{(n+1)!}\\prod_{i=0}^{n}(x-x_i), \\quad \\xi \\in (x_0, x_n)\n\\]\n\n**Note:** Lagrange does not require a difference table but is computationally heavier for large \\(n\\).\n\n### Inverse Interpolation\n\nGiven \\(y\\), find \\(x\\). Two methods:\n1. **Lagrange applied inversely** — swap roles of \\(x\\) and \\(y\\)\n2. **Iterative/successive approximation** using forward formula and solving for \\(p\\)\n\n> **ISS tip:** Divided difference symmetry and the relation \\(\\Delta^n f_0 = n!\\,h^n f[x_0,\\ldots,x_n]\\) are common MCQ targets. Also know that Lagrange can be derived from Newton's divided difference formula."
        },
        {
            "id": "num-integration",
            "label": "Numerical Integration",
            "content": "## Numerical Integration (Quadrature)\n\nAll rules below approximate \\(\\displaystyle I = \\int_a^b f(x)\\,dx\\) with \\(n\\) sub-intervals of width \\(h = (b-a)/n\\).\n\n---\n\n### Trapezoidal Rule\n\n\\(n\\) must be ≥ 1 (any integer).\n\n\\[\nI \\approx \\frac{h}{2}\\Bigl[f_0 + 2(f_1+f_2+\\cdots+f_{n-1}) + f_n\\Bigr]\n\\]\n\n**Error:** \\(\\displaystyle -\\frac{(b-a)h^2}{12}f''(\\xi)\\) — error is \\(O(h^2)\\).\n\n---\n\n### Simpson's 1/3 Rule\n\n**Requirement:** \\(n\\) must be **even**.\n\n\\[\nI \\approx \\frac{h}{3}\\Bigl[f_0 + 4f_1 + 2f_2 + 4f_3 + 2f_4 + \\cdots + 4f_{n-1} + f_n\\Bigr]\n\\]\n\nPattern of coefficients: **1, 4, 2, 4, 2, …, 4, 1**\n\n**Error:** \\(\\displaystyle -\\frac{(b-a)h^4}{180}f^{(4)}(\\xi)\\) — error is \\(O(h^4)\\). **Exact for polynomials up to degree 3.**\n\n---\n\n### Simpson's 3/8 Rule\n\n**Requirement:** \\(n\\) must be a **multiple of 3**.\n\n\\[\nI \\approx \\frac{3h}{8}\\Bigl[f_0 + 3f_1 + 3f_2 + 2f_3 + 3f_4 + 3f_5 + 2f_6 + \\cdots + f_n\\Bigr]\n\\]\n\nPattern: **1, 3, 3, 2, 3, 3, 2, …, 3, 3, 1**\n\n**Error:** \\(O(h^4)\\). **Exact for polynomials up to degree 3.**\n\n---\n\n### Weddle's Rule\n\n**Requirement:** \\(n\\) must be a **multiple of 6**.\n\n\\[\nI \\approx \\frac{3h}{10}\\Bigl[f_0 + 5f_1 + f_2 + 6f_3 + f_4 + 5f_5 + 2f_6 + 5f_7 + \\cdots + f_n\\Bigr]\n\\]\n\nPattern over each group of 6: **1, 5, 1, 6, 1, 5, 2** (last group ends with 1).\n\n**Error:** \\(O(h^6)\\). Very accurate for smooth functions.\n\n---\n\n### Comparison Table\n\n| Rule | Intervals needed | Coeff pattern | Exact for degree | Error order |\n|---|---|---|---|---|\n| Trapezoidal | any \\(n\\) | 1,2,2,...,2,1 | ≤1 | \\(O(h^2)\\) |\n| Simpson's 1/3 | even \\(n\\) | 1,4,2,4,...,4,1 | ≤3 | \\(O(h^4)\\) |\n| Simpson's 3/8 | mult. of 3 | 1,3,3,2,3,3,...,1 | ≤3 | \\(O(h^4)\\) |\n| Weddle's | mult. of 6 | 1,5,1,6,1,5,2,... | ≤5 | \\(O(h^6)\\) |\n\n> **ISS tip:** The most commonly tested facts are: Simpson's 1/3 requires **even** \\(n\\); its error is \\(O(h^4)\\) despite looking \\(O(h^2)\\); and the coefficient patterns. Weddle's rule is a special corrected form of the 3/8 rule."
        },
        {
            "id": "num-summation",
            "label": "Summation of Series",
            "content": "## Summation of Series\n\n### Case 1: General Term is \\(\\Delta f(r)\\)\n\nIf \\(t_r = \\Delta f(r) = f(r+1) - f(r)\\), then:\n\\[\n\\sum_{r=a}^{b} t_r = f(b+1) - f(a)\n\\]\nThis is the **discrete analogue of the Fundamental Theorem of Calculus**.\n\n**Example:** \\(\\sum r(r+1) = \\sum \\Delta\\!\\left(\\frac{r(r+1)(r+2)}{3}\\right)\\)\n\nUseful factorial-form antidifferences:\n\\[\n\\sum r^{(n)} = \\frac{r^{(n+1)}}{n+1} + C\n\\]\n\n### Case 2: General Term in Geometric Progression\n\nIf \\(t_r = A \\cdot x^r\\) (geometric):\n\\[\n\\sum_{r=0}^{n-1} A\\cdot x^r = A\\cdot\\frac{x^n - 1}{x - 1}, \\quad x \\neq 1\n\\]\n\nFor mixed terms like \\(t_r = P(r)\\cdot x^r\\) (poly × geometric), use the **summation by parts** technique:\n\\[\n\\sum u\\,\\Delta v = uv - \\sum Eu\\,\\Delta^{-1}(\\Delta v)\n\\]\n\n### Euler–Maclaurin Summation (reference)\n\n\\[\n\\sum_{r=a}^{b} f(r) = \\int_a^b f(x)\\,dx + \\tfrac{1}{2}[f(a)+f(b)] + \\sum_{k=1}^{p} \\frac{B_{2k}}{(2k)!}[f^{(2k-1)}(b) - f^{(2k-1)}(a)] + R_p\n\\]\n\nwhere \\(B_{2k}\\) are Bernoulli numbers: \\(B_2=1/6,\\;B_4=-1/30,\\ldots\\)\n\n> **ISS tip:** Most ISS questions on summation ask you to express the general term in factorial form, then apply the antidifference operator. Recognise \\(\\Delta(x^{(n)}) = n\\cdot x^{(n-1)}\\)."
        },
        {
            "id": "num-ode",
            "label": "Numerical Solution of ODEs",
            "content": "## Numerical Solutions of Differential Equations\n\nSolving \\(dy/dx = f(x,y)\\), \\(y(x_0) = y_0\\), step size \\(h\\).\n\n---\n\n### Euler's Method (Single-step, explicit)\n\n\\[\ny_{n+1} = y_n + h\\,f(x_n, y_n)\n\\]\n\n- Simplest method; **first-order** accurate, error \\(O(h^2)\\) per step, \\(O(h)\\) globally.\n- Geometrically: follow the tangent at each step.\n- Modified Euler (Heun's): predictor–corrector, \\(O(h^2)\\) accuracy.\n\n---\n\n### Picard's Method (Successive Approximation)\n\nBased on converting ODE to integral equation:\n\\[\ny(x) = y_0 + \\int_{x_0}^{x} f\\bigl(t, y(t)\\bigr)\\,dt\n\\]\n\nIterative scheme:\n\\[\ny^{(k+1)}(x) = y_0 + \\int_{x_0}^{x} f\\bigl(t, y^{(k)}(t)\\bigr)\\,dt, \\quad y^{(0)} = y_0\n\\]\n\n- Gives solution as a **power series** (polynomial approximation).\n- Not practical for large ranges; mainly theoretical.\n\n---\n\n### Runge–Kutta 4th Order Method (RK4)\n\nMost important method for ISS — **4th-order accurate**, error \\(O(h^4)\\) per step.\n\n\\[\nk_1 = h\\,f(x_n,\\, y_n)\n\\]\n\\[\nk_2 = h\\,f\\!\\left(x_n + \\tfrac{h}{2},\\; y_n + \\tfrac{k_1}{2}\\right)\n\\]\n\\[\nk_3 = h\\,f\\!\\left(x_n + \\tfrac{h}{2},\\; y_n + \\tfrac{k_2}{2}\\right)\n\\]\n\\[\nk_4 = h\\,f\\!\\left(x_n + h,\\; y_n + k_3\\right)\n\\]\n\\[\ny_{n+1} = y_n + \\tfrac{1}{6}(k_1 + 2k_2 + 2k_3 + k_4)\n\\]\n\nWeighted average: weights **1:2:2:1** summing to 6.\n\n---\n\n### Milne's Method (Multi-step, Predictor–Corrector)\n\n**Requires 4 prior values**: \\(y_{n-3}, y_{n-2}, y_{n-1}, y_n\\).\n\n**Predictor:**\n\\[\ny_{n+1}^{(P)} = y_{n-3} + \\frac{4h}{3}\\bigl[2f_n - f_{n-1} + 2f_{n-2}\\bigr]\n\\]\n\n**Corrector:**\n\\[\ny_{n+1}^{(C)} = y_{n-1} + \\frac{h}{3}\\bigl[f_{n-1} + 4f_n + f_{n+1}^{(P)}\\bigr]\n\\]\n\nThe corrector is Simpson's 1/3 rule applied to the ODE.\n\n---\n\n### Comparison\n\n| Method | Type | Starts from | Order | Notes |\n|---|---|---|---|---|\n| Euler | Single-step | \\(y_0\\) only | 1st | Simplest; low accuracy |\n| Picard | Single-step | \\(y_0\\) only | Series | Theoretical; exact in limit |\n| RK4 | Single-step | \\(y_0\\) only | 4th | Best single-step for ISS |\n| Milne | Multi-step | 4 prior values | 4th | Needs RK4 to start |\n\n> **ISS tip:** RK4 is the most tested. Know all four \\(k\\) values and the \\(1:2:2:1\\) weights. Milne is predictor–corrector — the corrector is Simpson's rule. Picard gives a polynomial approximation by repeated integration."
        }
    ],
    "tips": "**High-priority topics for ISS Numerical Analysis:**\n- Operator relations: \\(E = 1+\\Delta\\), \\(\\nabla = 1-E^{-1}\\), \\(hD = \\ln(1+\\Delta)\\)\n- Know *when* to use each interpolation formula (Forward/Backward/Stirling/Bessel)\n- Simpson's 1/3 needs **even** \\(n\\); error is \\(O(h^4)\\) — frequently confused with \\(O(h^2)\\)\n- RK4 weights: **1, 2, 2, 1** — memorise the four \\(k\\) formulae\n- Milne corrector = Simpson's 1/3 rule applied to the ODE\n- Differences of zero: \\(\\Delta^n(0) = n!\\)"
},
"comp": {
    "title": "Computer Application & Data Processing",
    "sections": [
        {
            "id": "comp-basics",
            "label": "Basics of a Computer System",
            "content": "## Basics of a Computer System\n\n### Operations of a Computer\n\nEvery computer performs five fundamental operations:\n1. **Input** — Accept data/instructions\n2. **Storage** — Store data & programs\n3. **Processing** — Perform arithmetic/logic\n4. **Output** — Produce results\n5. **Control** — Coordinate all units\n\n---\n\n### Major Units\n\n| Unit | Role |\n|---|---|\n| **CPU** (Central Processing Unit) | Brain of the computer; executes instructions |\n| **ALU** (Arithmetic & Logic Unit) | Arithmetic (+,−,×,÷) and logical (AND, OR, NOT, compare) operations |\n| **CU** (Control Unit) | Fetches, decodes, and executes instructions; directs data flow |\n| **Memory Unit** | Stores data and programs (primary & secondary) |\n| **Input Unit** | Keyboard, mouse, scanner, microphone, camera |\n| **Output Unit** | Monitor, printer, speaker, projector |\n\n**Von Neumann Architecture:** CPU + Memory + I/O connected via a **bus** (data bus, address bus, control bus).\n\n---\n\n### Memory Hierarchy\n\n| Level | Type | Speed | Capacity | Volatile? |\n|---|---|---|---|---|\n| Registers | CPU-internal | Fastest | Bytes | Yes |\n| Cache (L1/L2/L3) | SRAM | Very fast | KB–MB | Yes |\n| RAM | DRAM | Fast | GB | Yes |\n| ROM / EEPROM | — | Medium | MB | **No** |\n| SSD / HDD | Secondary | Slow | TB | No |\n\n**RAM** (Random Access Memory) — volatile; loses data on power off.\n**ROM** (Read-Only Memory) — non-volatile; holds BIOS/firmware.\n**Cache** — fastest memory between CPU and RAM.\n\n### Memory Units\n\n| Unit | Value |\n|---|---|\n| 1 Byte | 8 bits |\n| 1 KB (Kilobyte) | \\(2^{10}\\) = 1024 bytes |\n| 1 MB (Megabyte) | \\(2^{20}\\) bytes |\n| 1 GB (Gigabyte) | \\(2^{30}\\) bytes |\n| 1 TB (Terabyte) | \\(2^{40}\\) bytes |\n\n> **ISS tip:** ALU vs CU distinction is frequently tested. RAM = volatile, ROM = non-volatile. Know the memory hierarchy order."
        },
        {
            "id": "comp-number-systems",
            "label": "Number Systems",
            "content": "## Number Systems\n\n### Bases Used in Computing\n\n| System | Base | Digits |\n|---|---|---|\n| Binary | 2 | 0, 1 |\n| Octal | 8 | 0–7 |\n| Decimal | 10 | 0–9 |\n| Hexadecimal | 16 | 0–9, A–F |\n\n### Conversion Methods\n\n**Decimal → Binary:** Repeated division by 2; remainders read bottom-up.\n\n**Binary → Decimal:**\n\\[\n(1011)_2 = 1\\cdot2^3 + 0\\cdot2^2 + 1\\cdot2^1 + 1\\cdot2^0 = 8+0+2+1 = 11\n\\]\n\n**Binary ↔ Hexadecimal:** Group binary digits in sets of 4 from right.\n\\[\n(1010\\;1111)_2 = (AF)_{16}\n\\]\n\n**Binary ↔ Octal:** Group in sets of 3 from right.\n\\[\n(101\\;110)_2 = (56)_8\n\\]\n\n### Complements (for subtraction)\n\n**1's Complement:** Flip all bits. `1011` → `0100`\n\n**2's Complement:** 1's complement + 1. `1011` → `0100` + `1` = `0101`\n\nSubtraction in binary: \\(A - B = A + (\\text{2's complement of }B)\\)\n\n### BCD (Binary Coded Decimal)\n\nEach decimal digit stored as a 4-bit binary group.\n- Decimal `25` → BCD `0010 0101`\n- Addition in BCD: if sum of nibble > 9, add `0110` (6) to correct.\n\n### Important Powers of 2\n\n\\[\n2^8 = 256,\\quad 2^{10} = 1024,\\quad 2^{16} = 65536,\\quad 2^{32} \\approx 4.3 \\times 10^9\n\\]\n\n> **ISS tip:** Decimal↔Binary conversion is a guaranteed MCQ. Know 2's complement for subtraction. Hexadecimal grouping of 4 binary bits is very commonly tested."
        },
        {
            "id": "comp-software-os",
            "label": "Software, OS & Languages",
            "content": "## Software, Operating Systems & Languages\n\n### Types of Software\n\n```\nSoftware\n├── System Software\n│   ├── Operating System (Windows, Linux, macOS)\n│   ├── Compiler, Assembler, Interpreter\n│   ├── Device Drivers\n│   └── Utilities (disk defragmenter, antivirus)\n└── Application Software\n    ├── General Purpose (MS Word, Excel, browsers)\n    └── Special Purpose (billing software, statistical packages)\n```\n\n### Operating System (OS)\n\nThe OS manages:\n- **Process Management** — scheduling, multitasking\n- **Memory Management** — allocation, virtual memory\n- **File System** — FAT, NTFS, ext4\n- **I/O Management** — device drivers\n- **Security** — user authentication, permissions\n\nTypes: **Batch, Time-sharing, Real-time, Distributed, Network OS.**\n\n### Language Levels\n\n| Level | Example | Needs translation? |\n|---|---|---|\n| Machine Language | `10110001` | No |\n| Assembly Language | `MOV AX, 1` | Assembler |\n| High-Level Language | C, Python, Java | Compiler/Interpreter |\n\n### Translators\n\n| Translator | Input | Output | Execution |\n|---|---|---|---|\n| **Compiler** | HLL source | Machine code | After full translation |\n| **Interpreter** | HLL source | Executes line-by-line | During translation |\n| **Assembler** | Assembly | Machine code | After translation |\n\n**Linker** — combines object files.\n**Loader** — loads executable into memory.\n\n### Statistical Packages (ISS-relevant)\n\n- **SAS** — industry standard for statistical analysis\n- **SPSS** — social sciences, survey data\n- **R** — open-source, widely used in government statistics\n- **STATA** — econometrics and panel data\n\n> **ISS tip:** Compiler vs Interpreter distinction is frequently tested. Remember: compiler translates the whole program first; interpreter translates and executes line by line. Python is interpreted; C is compiled."
        },
        {
            "id": "comp-networking-security",
            "label": "Networking & Computer Security",
            "content": "## Networking & Computer Security\n\n### Types of Networks\n\n| Type | Full Form | Coverage | Example |\n|---|---|---|---|\n| **LAN** | Local Area Network | Room / Building | Office network |\n| **MAN** | Metropolitan Area Network | City | City-wide cable TV |\n| **WAN** | Wide Area Network | Country / Globe | Internet |\n| **PAN** | Personal Area Network | Few metres | Bluetooth |\n\n### Internet vs Intranet vs Extranet\n\n- **Internet** — public global network\n- **Intranet** — private internal network (within an organisation)\n- **Extranet** — controlled private network accessible to authorised outsiders\n\n### Network Protocols (key ones)\n\n| Protocol | Layer | Use |\n|---|---|---|\n| HTTP / HTTPS | Application | Web browsing |\n| FTP | Application | File transfer |\n| SMTP / POP3 / IMAP | Application | Email |\n| TCP | Transport | Reliable connection |\n| IP | Network | Addressing & routing |\n| DNS | Application | Domain → IP resolution |\n\n**IP Address:** IPv4 — 32-bit (e.g. `192.168.1.1`); IPv6 — 128-bit.\n\n### Computer Security Threats\n\n| Threat | Description |\n|---|---|\n| **Virus** | Self-replicating program that attaches to files |\n| **Worm** | Self-replicating; spreads over network without host file |\n| **Trojan** | Disguised as legitimate software; opens backdoor |\n| **Spyware** | Secretly collects user data |\n| **Malware** | Umbrella term for all malicious software |\n| **Ransomware** | Encrypts files; demands payment |\n| **Phishing** | Fraudulent emails/sites to steal credentials |\n\n### Security Measures\n\n- **Antivirus** — detects and removes malware\n- **Firewall** — filters incoming/outgoing network traffic (hardware or software)\n- **Encryption** — converts data to unreadable form (e.g. AES, RSA)\n- **Digital Signature** — verifies authenticity using asymmetric cryptography\n- **VPN** — encrypted tunnel over public network\n\n> **ISS tip:** LAN/WAN/MAN differences, virus vs worm vs trojan distinctions, and firewall function are very commonly tested MCQ topics."
        },
        {
            "id": "comp-programming-basics",
            "label": "Programming Fundamentals",
            "content": "## Programming Fundamentals\n\n### Algorithm & Flowchart\n\n**Algorithm** — step-by-step finite procedure to solve a problem.\nProperties: **Input, Output, Definiteness, Finiteness, Effectiveness.**\n\n**Flowchart symbols:**\n\n| Shape | Meaning |\n|---|---|\n| Oval | Start / Stop (Terminal) |\n| Rectangle | Process / Instruction |\n| Diamond | Decision (Yes/No) |\n| Parallelogram | Input / Output |\n| Arrow | Flow of control |\n\n---\n\n### Data Types & Variables\n\n| Type | Example values |\n|---|---|\n| Integer | `5`, `-3`, `0` |\n| Float/Real | `3.14`, `-2.7` |\n| Character | `'A'`, `'z'` |\n| Boolean | `True`, `False` |\n| String | `\"Statistics\"` |\n\n**Variable** — named memory location; must be declared before use in typed languages.\n\n---\n\n### Control Structures\n\n**Sequential** — statements execute in order.\n\n**Selection (Conditional):**\n```\nif condition:\n    statement_1\nelse:\n    statement_2\n```\n\n**Iteration (Loops):**\n- `for` loop — known number of iterations\n- `while` loop — condition-based\n- `do-while` — executes at least once\n\n---\n\n### Arrays\n\n- Contiguous memory; same data type; indexed from 0 (most languages)\n- **1D array:** `A[n]` — \\(n\\) elements\n- **2D array:** `A[m][n]` — \\(m \\times n\\) matrix\n- **Row-major** (C) vs **Column-major** (Fortran) storage\n\n---\n\n### Functions & Modules\n\n- **Function** — reusable named block of code; takes parameters, returns value\n- **Recursion** — function calls itself; needs a base case\n- **Module** — file containing related functions/classes\n\n---\n\n### Exception Handling\n\n```\ntry:\n    risky_code()\nexcept ErrorType:\n    handle_error()\nfinally:\n    always_runs()\n```\n\n---\n\n### Database Basics\n\n- **Data** — raw facts\n- **Information** — processed data with meaning\n- **Database** — organised collection of structured data\n- **DBMS** — software to manage databases (MySQL, Oracle, PostgreSQL)\n- **SQL** basics: `SELECT`, `INSERT`, `UPDATE`, `DELETE`, `WHERE`, `JOIN`\n- **Primary Key** — unique identifier for a record\n- **Foreign Key** — links two tables\n\n---\n\n### Frontend vs Backend\n\n| | Frontend | Backend |\n|---|---|---|\n| Also called | Client-side | Server-side |\n| Languages | HTML, CSS, JavaScript | Python, Java, PHP, Node.js |\n| Deals with | UI, user interaction | Logic, database, APIs |\n\n> **ISS tip:** Know flowchart symbols, loop types, and the difference between array row-major/column-major. Database concepts (primary key, SQL commands) and frontend vs backend distinction are common MCQ areas."
        },
        {
            "id": "comp-hardware-io",
            "label": "Hardware — Input, Output & Peripherals",
            "content": "## Hardware — Input, Output & Peripheral Devices\n\n### Input Devices\n\n| Device | Type of Input |\n|---|---|\n| Keyboard | Text / commands |\n| Mouse | Pointing / clicking |\n| Scanner | Image / document digitisation |\n| Microphone | Audio |\n| Webcam | Video / image |\n| Barcode reader | Product codes |\n| OMR (Optical Mark Reader) | Marks on paper (MCQ sheets) |\n| OCR (Optical Character Reader) | Printed text recognition |\n| Touchscreen | Touch input |\n\n### Output Devices\n\n| Device | Output Type |\n|---|---|\n| Monitor (CRT, LCD, LED) | Visual display |\n| Printer (Inkjet, Laser, Dot-matrix) | Hard copy |\n| Plotter | Large-scale diagrams / CAD |\n| Speaker | Audio |\n| Projector | Magnified display |\n\n### Secondary Storage Devices\n\n| Device | Technology | Notes |\n|---|---|---|\n| HDD (Hard Disk Drive) | Magnetic | High capacity; slower |\n| SSD (Solid State Drive) | Flash memory | Fast; no moving parts |\n| CD / DVD | Optical | CD: 700 MB; DVD: 4.7 GB |\n| Blu-ray | Optical | 25–50 GB |\n| USB Flash Drive | Flash | Portable |\n| Magnetic Tape | Magnetic | Backup; sequential access |\n\n### Bus Types\n\n- **Data Bus** — carries actual data (bidirectional)\n- **Address Bus** — carries memory addresses (unidirectional)\n- **Control Bus** — carries control signals\n\n### Ports & Interfaces\n\n| Port | Use |\n|---|---|\n| USB (Universal Serial Bus) | Most peripherals |\n| HDMI | Video/audio to display |\n| Ethernet (RJ-45) | Wired network |\n| Wi-Fi | Wireless network |\n| Bluetooth | Short-range wireless |\n\n> **ISS tip:** OMR is specifically used for MCQ answer sheets — very ISS-relevant context. Know the difference between input/output/storage devices. Printer types: inkjet (home), laser (office), dot-matrix (carbon copies)."
        }
    ],
    "tips": "**High-priority topics for ISS Computer section:**\n- Number system conversions: Decimal↔Binary, Binary↔Hex (group in 4s), 2's complement\n- Memory: RAM (volatile) vs ROM (non-volatile); 1 KB = 1024 bytes\n- Compiler (whole program first) vs Interpreter (line by line)\n- LAN < MAN < WAN in coverage\n- Virus (attaches to file) vs Worm (self-spreads on network) vs Trojan (disguised)\n- Flowchart: Diamond = Decision; Oval = Start/Stop\n- SQL: SELECT, INSERT, UPDATE, DELETE\n- Frontend (HTML/CSS/JS) vs Backend (Python/Java/PHP)"
},
    },
    "paper2": {
        "linear": {
            "title": "Linear Models",
            "sections": [
            ],
            "tips": ""
        },
        "inference": {
            "title": "Statistical Inference",
            "sections": [
            ],
            "tips": ""
        },
        "official": {
            "title": "Official Statistics",
            "sections": [
            ],
            "tips": ""
        },
    }
};











